require("lazy").setup({
  require("plugins.colorscheme"),
  require("plugins.cmp"),
  require("plugins.lsp"),
  require("plugins.nvim-tree"),
  require("plugins.presence"),
  require("plugins.lazygit"),
  require("plugins.gitsigns"),
  require("plugins.indent-blankline"),
  require("plugins.nvim-autopairs"),
  require("plugins.telescope"),
  require("plugins.lualine"),
})
